// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// init
void init();
RcppExport SEXP RpiR_init() {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    init();
    return R_NilValue;
END_RCPP
}
// readAnalog
int readAnalog();
RcppExport SEXP RpiR_readAnalog() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(readAnalog());
    return __result;
END_RCPP
}
