# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Initialize the Raspberry Pi for IO 
init <- function() {
    invisible(.Call('RpiR_init', PACKAGE = 'RpiR'))
}

#' Read an analog value fromt the Raspberry Pi
#' @param chan An integer vector of channel(s) for which we should
#'    read the analog value.
#' @return An integer vector describing the analog value on the 
#'    specified channel(s), ranging in value from 0-1024.
readAnalog <- function(chan) {
    .Call('RpiR_readAnalog', PACKAGE = 'RpiR', chan)
}

