# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

start_poll <- function(chan, ms = 1000, buffer_size = 1024L) {
    invisible(.Call('RpiR_start_poll', PACKAGE = 'RpiR', chan, ms, buffer_size))
}

stop_poll <- function(chan) {
    invisible(.Call('RpiR_stop_poll', PACKAGE = 'RpiR', chan))
}

read_val <- function(chan) {
    .Call('RpiR_read_val', PACKAGE = 'RpiR', chan)
}

#' Initialize the Raspberry Pi for IO 
init <- function(spi_channel = 0L, pin_base = 100L) {
    invisible(.Call('RpiR_init', PACKAGE = 'RpiR', spi_channel, pin_base))
}

#' Read an analog value fromt the Raspberry Pi
#' @param chan An integer vector of channel(s) for which we should
#'    read the analog value.
#' @return An integer vector describing the analog value on the 
#'    specified channel(s), ranging in value from 0-1024.
read_analog <- function(chan) {
    .Call('RpiR_read_analog', PACKAGE = 'RpiR', chan)
}

